export const WALLET_SELECTOR_OPEN = 'WALLET_SELECTOR_OPEN'
export const WALLET_SELECTOR_CLOSE = 'WALLET_SELECTOR_CLOSE'
export const SHOW_LOADING_SPINNER = 'SHOW_LOADING_SPINNER'
export const SET_SPINNER_MESSAGE = 'SET_SPINNER_MESSAGE'
