export const SET_USER_ACCOUNT_DATA = 'SET_USER_ACCOUNT_DATA'
export const SET_WEB3_INSTANCE = 'SET_WEB3_INSTANCE'
export const WALLET_SELECTOR_OPEN = 'WALLET_SELECTOR_OPEN'
export const WALLET_SELECTOR_CLOSE = 'WALLET_SELECTOR_CLOSE'
